# Generated by Django 3.2.3 on 2022-04-19 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TouristSpots',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dname', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=1000)),
                ('parking', models.BooleanField()),
                ('fee', models.CharField(max_length=100)),
                ('tollfreeno', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('timings', models.TimeField()),
                ('images', models.ImageField(upload_to='Placespics')),
            ],
        ),
    ]
