# Generated by Django 3.2.3 on 2022-04-19 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Places', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TouristSpots',
            new_name='TouristSpot',
        ),
    ]
