# Generated by Django 3.2.3 on 2022-04-19 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Places', '0002_rename_touristspots_touristspot'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristspot',
            name='Maplink',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='touristspot',
            name='timings',
            field=models.CharField(max_length=100),
        ),
    ]
