# Generated by Django 3.2.3 on 2022-04-19 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Places', '0004_travelagency'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TravelAgency',
            new_name='TravelAgencie',
        ),
    ]
