# Generated by Django 3.2.3 on 2022-04-20 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Places', '0006_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='touristspot',
            name='parking',
        ),
        migrations.AddField(
            model_name='touristspot',
            name='category',
            field=models.CharField(choices=[('Forts', 'Forts'), ('Wildlife', 'Wildlife'), ('Palaces', 'Palaces'), ('Lakes', 'Lakes'), ('Religious Places', 'Religious Places'), ('Others', 'Others')], default=1, max_length=30),
        ),
    ]
