# Generated by Django 3.2.3 on 2022-04-22 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Places', '0009_auto_20220423_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touristspot',
            name='parking',
            field=models.CharField(choices=[('Have', 'Have'), ("Don't have", "Don't have")], default='', max_length=30),
        ),
    ]
