# Generated by Django 3.2.3 on 2022-04-23 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Places', '0011_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='ip',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='status',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='update_at',
        ),
    ]
