# Generated by Django 3.2.3 on 2022-04-23 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Places', '0012_auto_20220423_1443'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='comments',
        ),
    ]
