# Generated by Django 3.2.3 on 2022-04-24 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Places', '0014_remove_comment_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='travelagencie',
            old_name='contact',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='travelagencie',
            old_name='location',
            new_name='contact_no',
        ),
        migrations.RenameField(
            model_name='travelagencie',
            old_name='name',
            new_name='firmname',
        ),
        migrations.AddField(
            model_name='travelagencie',
            name='contact_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='travelagencie',
            name='vehicle',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='travelagencie',
            name='images',
            field=models.ImageField(upload_to='travelagentpics'),
        ),
    ]
