# Generated by Django 3.2.3 on 2022-04-24 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Places', '0015_auto_20220424_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelagencie',
            name='Facilities',
            field=models.CharField(default='', max_length=100),
        ),
    ]
