# Generated by Django 3.2.3 on 2022-04-24 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Places', '0016_travelagencie_facilities'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelagencie',
            name='maplink',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
