# Generated by Django 3.2.3 on 2022-04-24 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Places', '0017_travelagencie_maplink'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('rating', models.IntegerField(default=1)),
                ('image', models.ImageField(upload_to='hotelpics')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Places.touristspot')),
            ],
        ),
    ]
